# Dockerfile
FROM php:8.2-apache


COPY 90-xdebug.ini "${PHP_INI_DIR}/conf.d"
# Instala extensoes e ferramentas necessarias
RUN apt-get update && apt-get install -y \
    libzip-dev zip unzip git curl libpq-dev \
    supervisor \
    && docker-php-ext-install zip sockets pdo pdo_mysql \
    && pecl install xdebug  && docker-php-ext-enable xdebug \
    && apt-get clean

# Instala Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json /var/www/html

RUN composer install --no-dev --prefer-dist --no-interaction

RUN a2enmod rewrite

WORKDIR /var/www/html

# Run composer dump-autoload to optimize the autoloader
RUN composer dump-autoload --optimize

# Ativa o mod_rewrite do Apache
RUN a2enmod rewrite

# Copia arquivos
COPY . /var/www/html
COPY apache/supervisord.conf /etc/supervisord.conf

# Permissões
RUN chown -R www-data:www-data /var/www/html

RUN chmod -R 777 /var/www/html/
RUN chown -R 777 /var/www/html/
RUN chmod -R 777 /var/www/html/logs/
RUN chown -R 777 /var/www/html/logs/


RUN sed -i 's/80/8081/g' /etc/apache2/ports.conf
RUN sed -i 's/:80>/:8081>/g' /etc/apache2/sites-available/000-default.conf

EXPOSE 8081

# Define entrypoint
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
