FROM php:8.2-zts

# Instala Apache + dependências
RUN apt-get update && apt-get install -y \
    apache2 \
    supervisor \
    unzip git curl zip libzip-dev \
    && pecl install parallel \
    && docker-php-ext-enable parallel \
    && docker-php-ext-install pdo pdo_mysql \
    && a2enmod rewrite \
    && apt-get clean

# Instala Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN a2enmod rewrite
# Copia composer.json e instala dependências
COPY composer.json /var/www/html/
WORKDIR /var/www/html
RUN composer install --no-interaction --prefer-dist

# Copia o restante do projeto
COPY . /var/www/html

# Copia config do supervisord
COPY apache/supervisord.conf /etc/supervisord.conf

RUN sed -i 's/80/8080/g' /etc/apache2/ports.conf
RUN sed -i 's/:80>/:8080>/g' /etc/apache2/sites-available/000-default.conf

EXPOSE 8081

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
